### ISSUE TITLE
Ficher export > Format date

### ISSUE THREAD

**Issue by kamel-adrea** [ADREAMutuelle/hub#3]
Merci de prendre en compte le format suivant concernant la date présente dans le fichier d'export : AAAA-MM-JJ HH:MM:SS

**Comment by Kevin-Adrea** [comment]
Euh tu es sûr pour l'espace dans le nom de fichier ?

**Comment by kamel-adrea** [comment]
Il faut entendre par "date présente dans le fichier", la colonne date dans le fichier csv :)
Concernant le nom du fichier : adrea_submission_AAAAMMJJ-HHMMSS.csv
