### ISSUE TITLE
Nouvelle livraison sources 26/04/2019

### ISSUE THREAD

**Issue by kamel-adrea** [ADREAMutuelle/hub#6]
Nouvelle livraison Pixies "Suite aux retours de Nicolas, voici les fichiers correctifs pour éviter le double appel au premier chargement du site."

https://we.tl/t-pfvwSF8vxn

**Comment by kamel-adrea** [comment]
En complément, livraison du 23/04 dont je n'étais pas destinataires : 

"J'ai ajouté le tracking des url au changement de ticket, et ai corrigé le bug remonté par Kamel vendredi.
Les modifications sont dispo ici : https://we.tl/t-i2DVQybu57  (toujours à placer dans le dossier public/)"

**Comment by Kevin-Adrea** [comment]
@kamel-adrea 

Donc, la deuxième en premier et la première en deuxième ?

**Comment by kamel-adrea** [comment]
@Kevin-Adrea  Oui c'est ça
